from _typeshed import Incomplete
from argparse import BooleanOptionalAction as BooleanOptionalAction
from collections.abc import Generator

def setup_logging() -> None: ...
def parse_numtext(numtext): ...
def round_list(lst, n_digits): ...
def add_input(parser, pages: bool = True) -> None: ...
def add_n_digits(parser) -> None: ...
def get_input(args, init_forms: bool = False, **kwargs): ...
def _postpeek_generator(value, iterator) -> Generator[Incomplete, Incomplete]: ...
def iterator_hasvalue(iterator): ...
