from _typeshed import Incomplete
from pypdfium2._cli._parsers import (
    BooleanOptionalAction as BooleanOptionalAction,
    add_input as add_input,
    get_input as get_input,
    iterator_hasvalue as iterator_hasvalue,
    setup_logging as setup_logging,
)

have_pil: Incomplete
have_cv2: Incomplete
logger: Incomplete

def _bitmap_wrapper_foreign_simple(width, height, format, *args, **kwargs): ...

BitmapMakers: Incomplete
ColorSchemeFields: Incomplete
ColorOpts: Incomplete
SampleTheme: Incomplete

def attach(parser): ...

class SavingEngine:
    args: Incomplete
    postproc_kwargs: Incomplete
    def __init__(self, saver_args, postproc_kwargs) -> None: ...
    def _get_path(self, i, ext): ...
    def __call__(self, i, bitmap, page) -> None: ...

class PILEngine(SavingEngine):
    def do_imports(self) -> None: ...
    _to_pil_hook: Incomplete
    def _saving_hook(self, out_path, bitmap, page, postproc_kwargs) -> None: ...
    @staticmethod
    def _invert_px_lightness(r, g, b): ...
    LINV_LUT_SIZE: int
    @classmethod
    def _get_linv_lut(cls): ...
    @classmethod
    def postprocess(cls, src_image, page, posconv, invert_lightness, exclude_images): ...

class NumpyPILEngine(PILEngine):
    def do_imports(self) -> None: ...
    @staticmethod
    def _to_pil_hook(bitmap): ...

class NumpyCV2Engine(SavingEngine):
    def do_imports(self) -> None: ...
    def _saving_hook(self, out_path, bitmap, page, postproc_kwargs) -> None: ...
    @classmethod
    def postprocess(cls, src_image, bitmap, page, invert_lightness, exclude_images): ...

def _render_parallel_init(logging_init, engine_init, input, password, may_init_forms, kwargs, engine) -> None: ...
def _render_job(i, pdf, kwargs, engine) -> None: ...
def _render_parallel_job(i) -> None: ...
def _do_nothing() -> None: ...
def main(args) -> None: ...
