from _typeshed import Incomplete

def color_tohex(color, rev_byteorder): ...
def set_callback(struct, fname, callback) -> None: ...
def is_stream(buf, spec: str = "r"): ...
def get_buffer(ptr, size): ...

class _buffer_reader:
    py_buffer: Incomplete
    def __init__(self, py_buffer) -> None: ...
    def __call__(self, _, position, p_buf_first, size): ...

class _buffer_writer:
    py_buffer: Incomplete
    def __init__(self, py_buffer) -> None: ...
    def __call__(self, _, p_data_first, size): ...

def get_bufreader(buffer): ...
def get_bufwriter(buffer): ...
def pages_c_array(pages): ...
