import pypdfium2.internal as pdfium_i
from _typeshed import Incomplete

__all__ = ["PdfAttachment"]

class PdfAttachment(pdfium_i.AutoCastable):
    raw: Incomplete
    pdf: Incomplete
    def __init__(self, raw, pdf) -> None: ...
    def get_name(self): ...
    def get_data(self): ...
    def set_data(self, data) -> None: ...
    def has_key(self, key): ...
    def get_value_type(self, key): ...
    def get_str_value(self, key): ...
    def set_str_value(self, key, value) -> None: ...
