from collections.abc import Generator
from typing import Any

import pypdfium2.internal as pdfium_i
from _typeshed import Incomplete

from .page import PdfPage

__all__ = ["PdfDocument", "PdfFormEnv", "PdfXObject", "PdfBookmark", "PdfDest"]

class PdfDocument(pdfium_i.AutoCloseable):
    _input: Incomplete
    _password: Incomplete
    _autoclose: Incomplete
    _data_holder: Incomplete
    _data_closer: Incomplete
    formenv: Incomplete
    raw: Incomplete
    def __init__(self, input, password=None, autoclose: bool = False) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *_) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def parent(self) -> None: ...
    @staticmethod
    def _close_impl(raw, data_holder, data_closer) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, i) -> PdfPage: ...
    def __delitem__(self, i) -> None: ...
    @classmethod
    def new(cls): ...
    def init_forms(self, config=None) -> None: ...
    def get_formtype(self): ...
    def get_pagemode(self): ...
    def is_tagged(self): ...
    def save(self, dest, version=None, flags: int = 0) -> None: ...
    def get_identifier(self, type=...): ...
    def get_version(self): ...
    def get_metadata_value(self, key): ...
    METADATA_KEYS: Incomplete
    def get_metadata_dict(self, skip_empty: bool = False): ...
    def count_attachments(self): ...
    def get_attachment(self, index): ...
    def new_attachment(self, name): ...
    def del_attachment(self, index) -> None: ...
    def get_page(self, index): ...
    def new_page(self, width, height, index=None): ...
    def del_page(self, index) -> None: ...
    def import_pages(self, pdf, pages=None, index=None) -> None: ...
    def get_page_size(self, index: int) -> tuple[Any, Any]: ...
    def get_page_label(self, index): ...
    def page_as_xobject(self, index, dest_pdf): ...
    def get_toc(
        self, max_depth: int = 15, parent=None, level: int = 0, seen=None
    ) -> Generator[Incomplete, Incomplete]: ...

class PdfFormEnv(pdfium_i.AutoCloseable):
    raw: Incomplete
    pdf: Incomplete
    config: Incomplete
    def __init__(self, raw, pdf, config) -> None: ...
    @property
    def parent(self): ...
    @staticmethod
    def _close_impl(raw, config, pdf) -> None: ...

class PdfXObject(pdfium_i.AutoCloseable):
    raw: Incomplete
    pdf: Incomplete
    def __init__(self, raw, pdf) -> None: ...
    @property
    def parent(self): ...
    def as_pageobject(self): ...

class PdfBookmark(pdfium_i.AutoCastable):
    raw: Incomplete
    pdf: Incomplete
    level: Incomplete
    def __init__(self, raw, pdf, level) -> None: ...
    def get_title(self): ...
    def get_count(self): ...
    def get_dest(self): ...

class PdfDest(pdfium_i.AutoCastable):
    raw: Incomplete
    pdf: Incomplete
    def __init__(self, raw, pdf) -> None: ...
    def get_index(self): ...
    def get_view(self): ...
