__all__ = ["PdfMatrix"]

class PdfMatrix:
    def __init__(self, a: int = 1, b: int = 0, c: int = 0, d: int = 1, e: int = 0, f: int = 0) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other): ...
    @property
    def _as_parameter_(self): ...
    def get(self): ...
    @classmethod
    def from_raw(cls, raw): ...
    def to_raw(self): ...
    def multiply(self, other): ...
    def translate(self, x, y): ...
    def scale(self, x, y): ...
    def rotate(self, angle, ccw: bool = False, rad: bool = False): ...
    def mirror(self, invert_x, invert_y): ...
    def skew(self, x_angle, y_angle, rad: bool = False): ...
    def on_point(self, x, y): ...
    def on_rect(self, left, bottom, right, top): ...
