import ctypes
from collections.abc import Callable, Generator
from typing import Any

import pypdfium2.internal as pdfium_i
from _typeshed import Incomplete

from .bitmap import PdfBitmap

__all__ = ["PdfPage", "PdfColorScheme"]

c_float = ctypes.c_float

class PdfPage(pdfium_i.AutoCloseable):
    raw: Incomplete
    pdf: Incomplete
    formenv: Incomplete
    def __init__(self, raw, pdf, formenv) -> None: ...
    @staticmethod
    def _close_impl(raw, formenv) -> None: ...
    @property
    def parent(self): ...
    def get_width(self): ...
    def get_height(self): ...
    def get_size(self): ...
    def get_rotation(self): ...
    def set_rotation(self, rotation) -> None: ...
    def _get_box(self, box_func, fallback_func, fallback_ok): ...
    def get_mediabox(self, fallback_ok: bool = True): ...
    def set_mediabox(self, l, b, r, t) -> None: ...
    def get_cropbox(self, fallback_ok: bool = True): ...
    def set_cropbox(self, l, b, r, t) -> None: ...
    def get_bleedbox(self, fallback_ok: bool = True): ...
    def set_bleedbox(self, l, b, r, t) -> None: ...
    def get_trimbox(self, fallback_ok: bool = True): ...
    def set_trimbox(self, l, b, r, t) -> None: ...
    def get_artbox(self, fallback_ok: bool = True): ...
    def set_artbox(self, l, b, r, t) -> None: ...
    def get_bbox(self): ...
    def get_textpage(self): ...
    def insert_obj(self, pageobj) -> None: ...
    def remove_obj(self, pageobj) -> None: ...
    def gen_content(self) -> None: ...
    def get_objects(
        self, filter=None, max_depth: int = 15, form=None, level: int = 0
    ) -> Generator[Incomplete, Incomplete]: ...
    def flatten(self, flag=...): ...
    def render(
        self,
        scale: float = 1,
        rotation: int = 0,
        crop: tuple[float, float, float, float]=(0, 0, 0, 0),
        may_draw_forms: bool = True,
        bitmap_maker:Callable[[Any, Any, Any, Any, Any, Any], PdfBitmap]=...,
        color_scheme: PdfColorScheme | None = None,
        fill_to_stroke: bool = False,
        **kwargs: Any,
    ) -> PdfBitmap: ...

class PdfColorScheme:
    colors: Incomplete
    def __init__(self, path_fill, path_stroke, text_fill, text_stroke) -> None: ...
    def __repr__(self) -> str: ...
    def convert(self, rev_byteorder): ...
