import pypdfium2.internal as pdfium_i
from _typeshed import Incomplete
from typing import NamedTuple

__all__ = ["PdfObject", "PdfImage", "PdfTextObj", "PdfFont"]

class PdfObject(pdfium_i.AutoCloseable):
    def __new__(cls, raw, *args, **kwargs): ...
    raw: Incomplete
    page: Incomplete
    pdf: Incomplete
    container: Incomplete
    level: Incomplete
    def __init__(self, raw, page=None, pdf=None, container=None, level: int = 0) -> None: ...
    @property
    def parent(self): ...
    def get_bounds(self): ...
    def get_quad_points(self): ...
    def get_matrix(self): ...
    def set_matrix(self, matrix) -> None: ...
    def transform(self, matrix) -> None: ...

class PdfTextObj(PdfObject):
    textpage: Incomplete
    def __init__(self, *args, textpage=None, **kwargs) -> None: ...
    def extract(self): ...
    def get_font(self): ...
    def get_font_size(self): ...

class PdfFont(pdfium_i.AutoCastable):
    raw: Incomplete
    parent: Incomplete
    def __init__(self, raw, parent=None) -> None: ...
    def _get_name_impl(self, api, which): ...
    def get_base_name(self): ...
    def get_family_name(self): ...
    def get_weight(self): ...

class PdfImage(PdfObject):
    SIMPLE_FILTERS: Incomplete
    @classmethod
    def new(cls, pdf): ...
    def get_metadata(self): ...
    def get_px_size(self): ...
    def load_jpeg(self, source, pages=None, inline: bool = False, autoclose: bool = True) -> None: ...
    def set_bitmap(self, bitmap, pages=None) -> None: ...
    def _get_rendered_bitmap(self, scale_to_original): ...
    def get_bitmap(self, render: bool = False, scale_to_original: bool = True): ...
    def get_data(self, decode_simple: bool = False): ...
    def get_filters(self, skip_simple: bool = False): ...
    def extract(self, dest, *args, **kwargs) -> None: ...

class _ImageInfo(NamedTuple):
    format: Incomplete
    mode: Incomplete
    metadata: Incomplete
    all_filters: Incomplete
    complex_filters: Incomplete

class _ImageExtractionError(Exception): ...
