import ctypes
import pypdfium2.internal as pdfium_i
from _typeshed import Incomplete

__all__ = ["PdfTextPage", "PdfTextSearcher"]

c_double = ctypes.c_double

class PdfTextPage(pdfium_i.AutoCloseable):
    raw: Incomplete
    page: Incomplete
    def __init__(self, raw, page) -> None: ...
    @property
    def parent(self): ...
    def get_text_bounded(self, left=None, bottom=None, right=None, top=None, errors: str = "ignore"): ...
    def _get_active_text_range(self, c_start, c_end, l_passive: int = 0, r_passive: int = 0): ...
    def get_text_range(self, index: int = 0, count: int = -1, errors: str = "ignore"): ...
    def count_chars(self): ...
    def count_rects(self, index: int = 0, count: int = -1): ...
    def get_index(self, x, y, x_tol, y_tol): ...
    def get_charbox(self, index, loose: bool = False): ...
    def get_rect(self, index): ...
    def get_textobj(self, index): ...
    def search(
        self,
        text,
        index: int = 0,
        match_case: bool = False,
        match_whole_word: bool = False,
        consecutive: bool = False,
        flags: int = 0,
    ): ...

class PdfTextSearcher(pdfium_i.AutoCloseable):
    raw: Incomplete
    textpage: Incomplete
    def __init__(self, raw, textpage) -> None: ...
    @property
    def parent(self): ...
    def _get_occurrence(self, find_func): ...
    def get_next(self): ...
    def get_prev(self): ...
