from _typeshed import Incomplete

__all__ = ["PdfUnspHandler"]

class PdfUnspHandler:
    handlers: Incomplete
    _config: Incomplete
    def __init__(self) -> None: ...
    def __call__(self, _, type) -> None: ...
    def setup(self, add_default: bool = True) -> None: ...
    def _keep(self) -> None: ...
    @staticmethod
    def _default(type) -> None: ...
